repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--line-length=120, --profile=black]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=120, --skip-string-normalization]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        language_version: python3.10
        args: [--max-line-length=120, --ignore=E203]